### ISSUE TITLE
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by Luamnoxu** [johnnymcmike/Gravital#10]
I really hope this is an error on my part but trying to launch this atm seem to result in 

```
(aibot) C:\Users\Maxim\Desktop\various\FUCK\AI>python main.py
Traceback (most recent call last):
  File "C:\Users\Maxim\Desktop\various\FUCK\AI\main.py", line 56, in <module>
    main()
  File "C:\Users\Maxim\Desktop\various\FUCK\AI\main.py", line 47, in main
    client = ChatBot(args.maxlines)
  File "C:\Users\Maxim\Desktop\various\FUCK\AI\Bot\bot.py", line 18, in __init__
    super().__init__()
TypeError: __init__() missing 1 required keyword-only argument: 'intents'
```
Not sure what could cause this as i have both discord and aitextgen installed (both most recent versions)
can provide more as needed

**Comment by johnnymcmike** [comment]
see #9 , it's kind of both on your end and my end, havent gotten around to fixing it yet but its easy for you to get around

**Comment by johnnymcmike** [comment]
oh and you'll also need to launch it with your token so doing `python main.py` just by itself won't ever work for unrelated reasons. you either do `python main.py --test` (which should work for you right now) to talk to it one-on-one in the command line, or you do it with --token to actually put it live on discord

**Comment by Luamnoxu** [comment]
oh no the not working without --token or --test i know about! usually it however says that it requires a token which is not what happened here
however some more info
I did install discord.py (was 2.0.1 before, now 2.0.0) and --test seems to run fine however --token [token] results in the same error as above

**Comment by Luamnoxu** [comment]
turns otu im an idiot! i forgot to install requirements.txt! apologies for the troubles

**Comment by johnnymcmike** [comment]
no problem enjoy :)
